export const libraries = [
  "nuxt/nuxt",
  "vuejs/core",
  "react/react",
  "sveltejs/svelte",
  "vitejs/vite",
  "vitest-dev/vitest",
  "vercel/next.js",
  "withastro/astro",
  "biomejs/biome",
  "tanstack/query-core",
  "solidjs/solid",
  "webpro-nl/knip",
  "eslint/eslint",
  "python/cpython",
  "rolldown/rolldown",
  "astral-sh/uv",
  "astral-sh/ruff",
] as const;

export const cicdBots = [
  "dependabot",
  "renovate",
  "greenkeeper",
  "github-actions",
  "stale",
  "snyk",
  "codecov",
  "coveralls",
  "travis",
  "circle",
  "appveyor",
  "azure-pipelines",
  "netlify",
  "vercel",
  "heroku",
  "aws-amplify",
  "eslintbot",
];
